#!/bin/bash
echo "########################  Setup Netmetric MoM  ########################"

#grupo no gentoo,archlinux,outras distros
#group=httpd
#No debian e ubuntu
#group=www-data
if [ ! -z "$1" ]
  then
	echo "######  Configurando Permissoes dos Diretorios data/*, cache e logs... #####"
	chmod ug+rwx data/* application/cache/ application/logs/
	chmod o-wx data/* application/cache/ application/logs/
#	ln -s /usr/share/netmetric-mom/public /var/www/mom
    	ln -s /usr/share/netmetric-mom/mom-apache.conf /etc/apache2/conf.d
	echo Permissoes OK


	echo "##### Configurando grupos dos arquivos para o do servidor web #####"
	chgrp -R $1 *

	echo "###### Criando a database no MySQL ######"

	mysql -u root < ./install/create-db.sql
	mysql -u root -D mom_dev < ./install/mom.sql
	mysql -u root -D mom_dev < ./install/mom_data.sql
	mysql -u root < ./install/mom_address.sql
	mysql -u root < ./install/mom_cep.sql
	mysql -u root < ./install/post-install.sql

#	echo "++++++++ Criando o arquivo public/.htaccess para o Apache"
	cp public/example.htaccess public/.htaccess
#	vim public/.htaccess
	
#	echo "++++++++ Criando os arquivos de configurações"
	cp application/config/database.php.example application/config/database.php
	cp application/config/network.php.example application/config/network.php
#	vim application/config/database.php

	cp ./install/redirector.php /var/www/index.php
	rm /var/www/index.html

	echo "###### Copiando a extensao do rrdtool para o PHP ######"
	cp ./install/rrdtool/rrdtool.so /usr/lib/php5/20090626/
	cp ./install/rrdtool/rrdtool.so /usr/lib/php5/20090626+lfs/
	cp ./install/rrdtool/rrdtool.ini /etc/php5/conf.d/

	echo "##### Ultimos ajustes do apache 2 #####"
	a2enmod rewrite
	cp ./install/ssl-cert-snakeoil.key /etc/ssl/private/
	cp ./install/ssl-cert-snakeoil.pem /etc/ssl/certs/
	chown root /etc/ssl/private/ssl-cert-snakeoil.key
	a2enmod ssl
	a2ensite default-ssl
	apache2ctl restart
	rm -rf ./install/post-install.sql
	php /usr/share/netmetric-mom/public/index.php --uri=tools/createResultTables
	echo "##### MoM Instalado #####"

else
	echo "Falta parametro obrigatorio: grupo usado pelo apache (ex: www-data no Ubuntu)"
	echo "Uso: setup <grupo-apache>"
#	echo "Ambiente de uso pode ser de production ou development"
fi
